config:
  validation: false

processors:
  active: true

build:
  maxIssues: 0
  weights:
    complexity: 2
    formatting: 1
    LongParameterList: 1
    comments: 1

formatting:
  active: true
  android: true

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

potential-bugs:
  active: true
  ExplicitGarbageCollectionCall:
    active: false