[versions]

# Android Build Info
namespace = "com.example.pokedexcompose"
compileSdk = "34"
applicationId = "com.example.pokedexcompose"
minSdk = "24"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
useSupportLibrary = "true"
releaseMinify = "false"
jvmTarget = "1.8"
composeProject = "true"
kotlinCompilerExtVersion = "1.5.1"


# AndroidX
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2023.08.00"

# Third Party
ktor = "2.3.9"

# Test
junit = "4.13.2"
junitExt = "1.1.5"
espresso = "3.5.1"

# Plugins
androidApplication = "8.2.1"
kotlinAndroid = "1.9.0"

[libraries]

# AndroidX
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }

# Third Party
ktor = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

# Test
junit = { module = "junit:junit", version.ref = "junit" }
junitExt = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
junitUiTest4 = { module = "androidx.compose.ui:ui-test-junit4" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]

androidApplication = { id = "com.android.application", version.ref = "androidApplication" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }