# Output dir
lint_dir = '**/build/reports/lint_result_debug.xml'

Dir[lint_dir].each do |file_name|
    android_lint.skip_gradle_task = true
    android_lint.report_file = file_name
    android_lint.lint(inline_mode: true)
end

message "Welcome, " + github.pr_author

failure "Please add labels to this PR" if github.pr_labels.empty?
failure "Please provide a summary in the Pull Request description" if github.pr_body.length < 5

warn "Watch the scale of your PR" if git.lines_of_code >= 500
failure "We cannot handle the scale of this PR" if git.lines_of_code > 1200
