name: AndroidBuild

on:
  pull_request:
    branches : [main, develop, infra/updating_git_hook]
  push :
    branches : [main, develop, infra/updating_git_hook]

jobs :
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution : 'temurin'
          java-version: 17
          cache: gradle

      - name: Grant gradlew execution permission
        run: chmod +x ./gradlew

      - name: Gradle build
        run: ./gradlew assembleDebug --stacktrace

      - name: Check build status
        run: |
          if [ $? -eq 0 ]; then
            echo "Build successful."
          else
            echo "Build failed."
            exit 1
          fi

  test:
    needs: build
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "termurin"
          cache: gradle

      - name: Grant gradlew execution permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Check unit tests status
        run: |
          if [ $? -eq 0 ]; then
            echo "Unit tests passed."
          else
            echo "Unit tests failed."
            exit 1
          fi 

#      - name: Upload built artifact
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: debug.apk
#          path: app/build/outputs/apk/debug/app-debug.apk