name: Android Debug Pipeline

on:
  pull_request:
    branches : [main, develop]
  push :
    branches : [main, develop]

jobs :
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution : 'temurin'
          java-version: 17
          cache: gradle

      - name: Grant gradlew execution permission
        run: chmod +x ./gradlew

      - name: Gradle build
        run: ./gradlew assembleDebug --stacktrace

      - name: Check build status
        run: |
          if [ $? -eq 0 ]; then
            echo "Build successful."
          else
            echo "Build failed."
            exit 1
          fi

  test:
    needs: build
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Grant gradlew execution permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Check unit tests status
        run: |
          if [ $? -eq 0 ]; then
            echo "Unit tests passed."
          else
            echo "Unit tests failed."
            exit 1
          fi